blueprint:
  name: Alarmo keypad management
  description: Keypad management for Alarmo with Zigbee2MQTT.
  domain: automation

  input:
    state_topic:
      name: MQTT State Topic of your Zigbee2MQTT Keypad
      description:
        "The State Topic is composed of your Zigbee2MQTT base_topic (see your Z2M Addon
        Configuration) and the Friendly Name of your keypad in Z2M. Example: zigbee2mqtt/Keypad"
      selector:
        text:
    set_topic:
      name: MQTT Set Topic of your Zigbee2MQTT Keypad
      description:
        "This is the same as your State Topic, with the addition of /set. Example:
        zigbee2mqtt/Keypad/set"
      selector:
        text:
    entity:
      name: Alarmo entity
      description: An alarm control panel entity from alarmo.
      selector:
        entity:
          domain: alarm_control_panel
          integration: alarmo

mode: parallel
max: 10

triggers:
  - trigger: state
    entity_id: !input entity
    to: disarmed
    id: to_state_disarmed
  - trigger: state
    entity_id: !input entity
    to: armed_custom_bypass
    id: to_state_armed_custom
  - trigger: state
    entity_id: !input entity
    to: armed_vacation
    id: to_state_armed_vacation
  - trigger: state
    entity_id: !input entity
    to: armed_night
    id: to_state_armed_night
  - trigger: state
    entity_id: !input entity
    to: armed_home
    id: to_state_armed_home
  - trigger: state
    entity_id: !input entity
    to: armed_away
    id: to_state_armed_away
  - trigger: state
    entity_id: !input entity
    to: arming
    id: to_state_arming
  - trigger: state
    entity_id: !input entity
    to: pending
    id: to_state_pending
  - trigger: state
    entity_id: !input entity
    to: triggered
    id: to_state_triggered
  - trigger: mqtt
    topic: !input state_topic
    id: keypad_command
  - trigger: event
    event_type: alarmo_failed_to_arm
    id: event_arm_failure
  - trigger: event
    event_type: alarmo_command_success
    id: event_command_success

action:
  - choose:
      - conditions:
          - condition: trigger
            id: to_state_disarmed
        sequence:
          - service: mqtt.publish
            data_template:
              topic: !input set_topic
              payload: |-
                {
                  "arm_mode":
                  {
                    "mode": "disarm"
                  }
                }
      - conditions:
          - condition: trigger
            id: to_state_armed_night
        sequence:
          - service: mqtt.publish
            data_template:
              topic: !input set_topic
              payload: |-
                {
                  "arm_mode":
                  {
                    "mode": "arm_night_zones"
                  }
                }
      - conditions:
          - condition: trigger
            id: to_state_armed_home
        sequence:
          - service: mqtt.publish
            data_template:
              topic: !input set_topic
              payload: |-
                {
                  "arm_mode":
                  {
                    "mode": "arm_day_zones"
                  }
                }
      - conditions:
          - condition: trigger
            id:
              - to_state_armed_away
              - to_state_armed_vacation
              - to_state_armed_custom
        sequence:
          - service: mqtt.publish
            data_template:
              topic: !input set_topic
              payload: |-
                {
                  "arm_mode":
                  {
                    "mode": "arm_all_zones"
                  }
                }
      - conditions:
          - condition: trigger
            id: to_state_arming
        sequence:
          - service: mqtt.publish
            data_template:
              topic: !input set_topic
              payload: |-
                {
                  "arm_mode":
                  {
                    "mode": "exit_delay"
                  }
                }
      - conditions:
          - condition: trigger
            id: to_state_pending
        sequence:
          - service: mqtt.publish
            data_template:
              topic: !input set_topic
              payload: |-
                {
                  "arm_mode":
                  {
                    "mode": "entry_delay"
                  }
                }
      - conditions:
          - condition: trigger
            id: to_state_triggered
        sequence:
          - service: mqtt.publish
            data_template:
              topic: !input set_topic
              payload: |-
                {
                  "arm_mode":
                  {
                    "mode": "in_alarm"
                  }
                }
      - conditions:
          - condition: trigger
            id: keypad_command
        sequence:
          - choose:
              - conditions:
                  - condition: template
                    value_template: '{{ trigger.payload_json.action == "disarm" }}'
                sequence:
                  - service: alarmo.disarm
                    data:
                      entity_id: !input entity
                      code: "{{ trigger.payload_json.action_code }}"
                      context_id: "{{ trigger.payload_json.action_transaction }}"
              - conditions:
                  - condition: template
                    value_template: '{{ trigger.payload_json.action == "arm_all_zones" }}'
                sequence:
                  - service: alarmo.arm
                    data:
                      entity_id: !input entity
                      mode: away
                      code: "{{ trigger.payload_json.action_code }}"
                      context_id: "{{ trigger.payload_json.action_transaction }}"
              - conditions:
                  - condition: template
                    value_template: '{{ trigger.payload_json.action == "arm_day_zones" }}'
                sequence:
                  - service: alarmo.arm
                    data:
                      entity_id: !input entity
                      mode: home
                      code: "{{ trigger.payload_json.action_code }}"
                      context_id: "{{ trigger.payload_json.action_transaction }}"
              - conditions:
                  - condition: template
                    value_template: '{{ trigger.payload_json.action == "arm_night_zones" }}'
                sequence:
                  - service: alarmo.arm
                    data:
                      entity_id: !input entity
                      mode: night
                      code: "{{ trigger.payload_json.action_code }}"
                      context_id: "{{ trigger.payload_json.action_transaction }}"
      - conditions:
          - condition: trigger
            id: event_arm_failure
        sequence:
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ trigger.event.data.reason == 'invalid_code' }}"
                sequence:
                  - service: mqtt.publish
                    data_template:
                      topic: !input set_topic
                      payload: |-
                        {
                          "arm_mode":
                          {
                            "transaction": {{ trigger.event.data.context_id }},
                            "mode": "invalid_code"
                          }
                        }
              - conditions:
                  - condition: template
                    value_template: "{{ trigger.event.data.reason == 'open_sensors' }}"
                sequence:
                  - service: mqtt.publish
                    data_template:
                      topic: !input set_topic
                      payload: |-
                        {
                          "arm_mode":
                          {
                            "transaction": {{ trigger.event.data.context_id }},
                            "mode": "not_ready"
                          }
                        }
              - conditions:
                  - condition: template
                    value_template: "{{ trigger.event.data.reason == 'not_allowed' }}"
                  - condition: template
                    value_template: "{{ trigger.event.data.command|lower == 'disarm' }}"
                sequence:
                  - service: mqtt.publish
                    data_template:
                      topic: !input set_topic
                      payload: |-
                        {
                          "arm_mode":
                          {
                            "transaction": {{ trigger.event.data.context_id }},
                            "mode": "already_disarmed"
                          }
                        }
      - conditions:
          - condition: trigger
            id: event_command_success
        sequence:
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ trigger.event.data.action == 'arm' }}"
                  - condition: template
                    value_template: "{{ trigger.event.data.context_id != null }}"
                  - condition: template
                    value_template:
                      "{{ trigger.event.data.mode in ['away', 'vacation', 'custom'] }}"
                sequence:
                  - service: mqtt.publish
                    data_template:
                      topic: !input set_topic
                      payload: |-
                        {
                          "arm_mode":
                          {
                            "transaction": {{ trigger.event.data.context_id }},
                            "mode": "arm_all_zones"
                          }
                        }
              - conditions:
                  - condition: template
                    value_template: "{{ trigger.event.data.action == 'arm' }}"
                  - condition: template
                    value_template: "{{ trigger.event.data.context_id != null }}"
                  - condition: template
                    value_template: "{{ trigger.event.data.mode == 'home' }}"
                sequence:
                  - service: mqtt.publish
                    data_template:
                      topic: !input set_topic
                      payload: |-
                        {
                          "arm_mode":
                          {
                            "transaction": {{ trigger.event.data.context_id }},
                            "mode": "arm_day_zones"
                          }
                        }
              - conditions:
                  - condition: template
                    value_template: "{{ trigger.event.data.action == 'arm' }}"
                  - condition: template
                    value_template: "{{ trigger.event.data.context_id != null }}"
                  - condition: template
                    value_template: "{{ trigger.event.data.mode == 'night' }}"
                sequence:
                  - service: mqtt.publish
                    data_template:
                      topic: !input set_topic
                      payload: |-
                        {
                          "arm_mode":
                          {
                            "transaction": {{ trigger.event.data.context_id }},
                            "mode": "arm_night_zones"
                          }
                        }
              - conditions:
                  - condition: template
                    value_template: "{{ trigger.event.data.action == 'disarm' }}"
                  - condition: template
                    value_template: "{{ trigger.event.data.context_id != null }}"
                sequence:
                  - service: mqtt.publish
                    data_template:
                      topic: !input set_topic
                      payload: |-
                        {
                          "arm_mode":
                          {
                            "transaction": {{ trigger.event.data.context_id }},
                            "mode": "disarm"
                          }
                        }
